version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es/elasticsearch.key
      - xpack.security.http.ssl.certificate=certs/es/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=certs/es/elasticsearch.key
      - xpack.security.transport.ssl.certificate=certs/es/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
      - ./data/certs/ca:/usr/share/elasticsearch/config/certs/ca
      - ./data/certs/es:/usr/share/elasticsearch/config/certs/es

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    restart: always
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_ENABLE_SSL=true
      - SPLUNK_SERVER_CERT=/opt/splunk/certs/splunk/splunk.crt
      - SPLUNK_SERVER_CERT_KEY=/opt/splunk/certs/splunk/splunk.key
      - SPLUNK_CA_CERT=/opt/splunk/certs/ca/ca.crt
      - SPLUNK_JAVA_OPTS=-Xms4096m -Xmx4096m
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    depends_on:
      - elasticsearch
    volumes:
      - ./data/splunk/data:/opt/splunk/var
      - ./data/splunk/apps:/opt/splunk/etc/apps
      - ./data/certs/ca:/opt/splunk/certs/ca
      - ./data/certs/splunk:/opt/splunk/certs/splunk
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8089"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  esdata:
    driver: local
