version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=config/certs/es/elasticsearch.key
      - xpack.security.http.ssl.certificate=config/certs/es/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=config/certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=config/certs/es/elasticsearch.key
      - xpack.security.transport.ssl.certificate=config/certs/es/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=config/certs/ca/ca.crt
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./data/certs/ca:/usr/share/elasticsearch/config/certs/ca
      - ./data/certs/es:/usr/share/elasticsearch/config/certs/es

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    depends_on:
      - elasticsearch
    volumes:
      - ./splunk/data:/opt/splunk/var
      - ./splunk/apps:/opt/splunk/etc/apps
      - ./data/certs/ca:/opt/splunk/certs/ca
      - ./data/certs/splunk:/opt/splunk/certs/splunk

volumes:
  esdata:
    driver: local
